#!/usr/bin/env python3
"""Generate a simple 2D Fluent ASCII channel mesh for UCNS3D."""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_XMIN = -0.25
DEFAULT_XMAX = 0.25
DEFAULT_YMIN = 0.0
DEFAULT_YMAX = 0.1
DEFAULT_X_CENTER_MIN = -0.15
DEFAULT_X_CENTER_MAX = 0.15


def hx(value: int) -> str:
    return format(value, "x")


def node_id(i: int, j: int, nx: int) -> int:
    return j * (nx + 1) + i + 1


def cell_id(i: int, j: int, nx: int) -> int:
    return j * nx + i + 1


def write_cell_types(handle, cell_count: int) -> None:
    for start in range(1, cell_count + 1, 16):
        count = min(16, cell_count - start + 1)
        handle.write(" " + " ".join("3" for _ in range(count)) + "\n")


def write_faces(handle, faces: list[tuple[int, int, int, int]]) -> None:
    for n0, n1, c0, c1 in faces:
        handle.write(f"2 {hx(n0)} {hx(n1)} {hx(c0)} {hx(c1)}\n")


def linspace(start: float, stop: float, intervals: int) -> list[float]:
    if intervals < 1:
        raise ValueError("interval count must be positive")
    delta = (stop - start) / intervals
    return [start + i * delta for i in range(intervals + 1)]


def piecewise_x(
    xmin: float,
    xmax: float,
    x_center_min: float,
    x_center_max: float,
    nx: int,
    x_left_cells: int | None,
    x_center_cells: int | None,
    x_right_cells: int | None,
) -> list[float]:
    if x_left_cells is None and x_center_cells is None and x_right_cells is None:
        return linspace(xmin, xmax, nx)

    missing = [
        name
        for name, value in (
            ("x_left_cells", x_left_cells),
            ("x_center_cells", x_center_cells),
            ("x_right_cells", x_right_cells),
        )
        if value is None
    ]
    if missing:
        raise ValueError(
            "piecewise x spacing requires --x-left-cells, --x-center-cells, "
            "and --x-right-cells"
        )
    if not (xmin < x_center_min < x_center_max < xmax):
        raise ValueError("expected xmin < x-center-min < x-center-max < xmax")

    left = linspace(xmin, x_center_min, x_left_cells)
    center = linspace(x_center_min, x_center_max, x_center_cells)
    right = linspace(x_center_max, xmax, x_right_cells)
    return left[:-1] + center[:-1] + right


def build_faces(nx: int, ny: int) -> dict[str, list[tuple[int, int, int, int]]]:
    faces: dict[str, list[tuple[int, int, int, int]]] = {
        "interior": [],
        "inlet": [],
        "outflow": [],
        "wall": [],
    }

    for j in range(ny):
        for i in range(1, nx):
            left = cell_id(i - 1, j, nx)
            right = cell_id(i, j, nx)
            faces["interior"].append(
                (node_id(i, j, nx), node_id(i, j + 1, nx), left, right)
            )

    for j in range(1, ny):
        for i in range(nx):
            bottom = cell_id(i, j - 1, nx)
            top = cell_id(i, j, nx)
            faces["interior"].append(
                (node_id(i, j, nx), node_id(i + 1, j, nx), bottom, top)
            )

    for j in range(ny):
        faces["inlet"].append(
            (node_id(0, j + 1, nx), node_id(0, j, nx), cell_id(0, j, nx), 0)
        )
        faces["outflow"].append(
            (node_id(nx, j, nx), node_id(nx, j + 1, nx), cell_id(nx - 1, j, nx), 0)
        )

    for i in range(nx):
        faces["wall"].append(
            (node_id(i, 0, nx), node_id(i + 1, 0, nx), cell_id(i, 0, nx), 0)
        )
        faces["wall"].append(
            (
                node_id(i + 1, ny, nx),
                node_id(i, ny, nx),
                cell_id(i, ny - 1, nx),
                0,
            )
        )

    return faces


def write_mesh(path: Path, xs: list[float], ys: list[float]) -> None:
    nx = len(xs) - 1
    ny = len(ys) - 1
    node_count = (nx + 1) * (ny + 1)
    cell_count = nx * ny
    faces = build_faces(nx, ny)
    boundary_count = len(faces["inlet"]) + len(faces["outflow"]) + len(faces["wall"])
    face_count = len(faces["interior"]) + boundary_count

    with path.open("w", encoding="ascii") as handle:
        handle.write('(1 "Generated by meshing/make_channel_mesh.py")\n')
        handle.write('\n(0 "Dimension : 2")\n')
        handle.write("(2 2)\n\n")
        handle.write(f'(0 "Number of Nodes : {node_count}")\n')
        handle.write(f"(10 (0 1 {hx(node_count)} 0 2))\n\n")
        handle.write(f'(0 "Total Number of Faces : {face_count}")\n')
        handle.write(f'(0 "       Boundary Faces : {boundary_count}")\n')
        handle.write(f'(0 "       Interior Faces : {len(faces["interior"])}")\n')
        handle.write(f"(13 (0 1 {hx(face_count)} 0))\n\n")
        handle.write(f'(0 "Total Number of Cells : {cell_count}")\n')
        handle.write('(0 "            Tri cells : 0")\n')
        handle.write(f'(0 "           Quad cells : {cell_count}")\n')
        handle.write('(0 "        Polygon cells : 0")\n')
        handle.write(f"(12 (0 1 {hx(cell_count)} 0))\n\n")

        handle.write(f'(0 "Zone 1  Number of Nodes : {node_count}")\n')
        handle.write(f"(10 (1 1 {hx(node_count)} 1 2)(\n")
        for y in ys:
            for x in xs:
                handle.write(f"{x: .15e} {y: .15e}\n")
        handle.write("))\n\n")

        handle.write(f'(0 "Zone 2  Number of Cells : {cell_count}")\n')
        handle.write(f"(12 (1 1 {hx(cell_count)} 1 3)(\n")
        write_cell_types(handle, cell_count)
        handle.write("))\n")
        handle.write("(45 (2 fluid unspecified)())\n\n")

        face_start = 1
        face_end = face_start + len(faces["interior"]) - 1
        handle.write(f'(0 "Zone 3 {len(faces["interior"])} faces {face_start}..{face_end}, Interior")\n')
        handle.write(f"(13 (3 {hx(face_start)} {hx(face_end)} 2 0)(\n")
        write_faces(handle, faces["interior"])
        handle.write("))\n")
        handle.write("(45 (3 interior interior-unspecified)())\n\n")

        zone_specs = [
            ("inlet", 4, "velocity-inlet", "bc-2", 10),
            ("outflow", 5, "outflow", "bc-3", 36),
            ("wall", 6, "wall", "bc-4", 3),
        ]
        for key, zone_id, bc_name, bc_label, bc_type in zone_specs:
            zone_faces = faces[key]
            face_start = face_end + 1
            face_end = face_start + len(zone_faces) - 1
            handle.write(
                f'(0 "Zone {zone_id} {len(zone_faces)} faces '
                f'{face_start}..{face_end}, BC: {bc_label} {bc_name} = {bc_type}")\n'
            )
            handle.write(f"(13 ({zone_id} {hx(face_start)} {hx(face_end)} {hx(bc_type)} 0)(\n")
            write_faces(handle, zone_faces)
            handle.write("))\n")
            handle.write(f"(45 ({zone_id} {bc_name} {bc_label})())\n\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("grid.msh"))
    parser.add_argument("--xmin", type=float, default=DEFAULT_XMIN)
    parser.add_argument("--xmax", type=float, default=DEFAULT_XMAX)
    parser.add_argument("--ymin", type=float, default=DEFAULT_YMIN)
    parser.add_argument("--ymax", type=float, default=DEFAULT_YMAX)
    parser.add_argument("--nx", type=int, default=60)
    parser.add_argument("--ny", type=int, default=20)
    parser.add_argument("--x-center-min", type=float, default=DEFAULT_X_CENTER_MIN)
    parser.add_argument("--x-center-max", type=float, default=DEFAULT_X_CENTER_MAX)
    parser.add_argument("--x-left-cells", type=int)
    parser.add_argument("--x-center-cells", type=int)
    parser.add_argument("--x-right-cells", type=int)
    args = parser.parse_args()
    if args.nx < 1 or args.ny < 1:
        parser.error("--nx and --ny must both be positive")
    if args.xmax <= args.xmin or args.ymax <= args.ymin:
        parser.error("domain maximums must exceed minimums")
    return args


def main() -> None:
    args = parse_args()
    try:
        xs = piecewise_x(
            args.xmin,
            args.xmax,
            args.x_center_min,
            args.x_center_max,
            args.nx,
            args.x_left_cells,
            args.x_center_cells,
            args.x_right_cells,
        )
    except ValueError as exc:
        raise SystemExit(f"error: {exc}") from exc
    ys = linspace(args.ymin, args.ymax, args.ny)
    write_mesh(args.output, xs, ys)


if __name__ == "__main__":
    main()
