#!/usr/bin/env python3
"""Example Python driver for a UCNS3D/pymoo/Slurm optimisation.

Edit PARAMETERS, make_case(), and objective() for the study being run. The
driver can first be used with --prepare-only to inspect generated cases without
submitting anything.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from analysis.compute_ucns3d_metrics import write_metrics_json  # noqa: E402
from cases.generate_cases import (  # noqa: E402
    Bubble,
    CaseConfig,
    Domain,
    Material,
    mesh_resolution_from_h,
    normal_shock_state,
)
from optimisation.ucns3d_pymoo import (  # noqa: E402
    Parameter,
    add_common_arguments,
    launch_controller,
    run_optimisation,
    slurm_from_args,
)

AIR = Material("air", gamma=1.4, density=1.198, sound_speed=344.0)
HELIUM_MIX = Material("helium_mixture", gamma=1.48, density=0.216, sound_speed=833.0)
AMBIENT_PRESSURE = 101_325.0
TEST_SECTION_HALF_HEIGHT = 0.0445
CYLINDER_DIAMETER = 0.05
DOMAIN = Domain(
    xmin=-0.35,
    xmax=0.25,
    ymin=-TEST_SECTION_HALF_HEIGHT,
    ymax=TEST_SECTION_HALF_HEIGHT,
    refined_xmin=-0.050,
    refined_xmax=0.055,
)

PARAMETERS = (
    Parameter("bubble_x", -0.010, 0.010),
    Parameter("bubble_y", -0.0065, 0.0065),
    Parameter("bubble_diameter", 0.040, 0.060),
    Parameter("bubble_density", 0.150, 0.300),
)


def make_case(values: dict[str, float], evaluation_index: int) -> CaseConfig:
    shock = normal_shock_state(1.22, AIR, AMBIENT_PRESSURE)
    h = CYLINDER_DIAMETER / 40.0
    return CaseConfig(
        name=f"eval_{evaluation_index:06d}",
        description="Optimisation evaluation generated by optimisation/example_driver.py.",
        ambient_material=AIR,
        shock=shock,
        domain=DOMAIN,
        mesh=mesh_resolution_from_h(DOMAIN, h, buffer_factor=2.0),
        shock_position_x=0.100,
        final_time=20.0e-6,
        output_interval=20.0e-6,
        bubbles=(
            Bubble(
                material=HELIUM_MIX,
                center=(values["bubble_x"], values["bubble_y"], 0.0),
                diameter=values["bubble_diameter"],
                density=values["bubble_density"],
            ),
        ),
        characteristic_length=values["bubble_diameter"],
        job_name=f"opt-{evaluation_index:06d}",
    )


def objective(run_dir: Path, values: dict[str, float]) -> tuple[float, float, float]:
    """Return pymoo minimisation objectives from UCNS3D VTU/PVTU metrics."""
    metrics = write_metrics_json(
        {
            "output_dir": run_dir,
            "json_out": run_dir / "metrics.json",
            "pressure_field": "pressure",
            "bad_material_field": "volume_fraction",
            "p_incident": 1.0,
            "p0": AMBIENT_PRESSURE,
            "t_ref": 1.0e-6,
            "target_region": {
                "type": "circle",
                "xc": values["bubble_x"],
                "yc": values["bubble_y"],
                "radius": 0.5 * values["bubble_diameter"],
            },
            "interaction_region": {
                "type": "box",
                "xmin": DOMAIN.refined_xmin,
                "xmax": DOMAIN.refined_xmax,
                "ymin": DOMAIN.ymin,
                "ymax": DOMAIN.ymax,
            },
        }
    )
    return (
        -metrics["Ap95_target"],
        -metrics["Ip_target"],
        metrics["Mbad_target"],
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    add_common_arguments(parser)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.launch_controller:
        if args.prepare_only:
            raise ValueError("--launch-controller cannot be combined with --prepare-only")
        job_id = launch_controller(
            driver=Path(__file__),
            argv=sys.argv[1:],
            work_dir=args.work_dir,
            wall_time=args.controller_time,
            partition=args.controller_partition,
        )
        print(f"submitted optimisation controller job {job_id}")
        print(f"controller script: {(args.work_dir / 'optimisation-controller.jcf').resolve()}")
        return
    run_optimisation(
        parameters=PARAMETERS,
        make_case=make_case,
        objective=objective,
        n_obj=3,
        work_dir=args.work_dir,
        slurm=slurm_from_args(args),
        generations=args.generations,
        population=args.population,
        algorithm_name=args.algorithm,
        seed=args.seed,
        prepare_only=args.prepare_only,
        submit_jobs=args.submit,
        poll_interval=args.poll_interval,
        max_concurrent=args.max_concurrent,
        failure_penalty=args.failure_penalty,
        resume=args.resume,
    )


if __name__ == "__main__":
    main()
